Feature/expanded logs
COPRS/monitoring pull request #51
Opened 2022-12-21 13:58 UTC by RomainDUCLERCQ

Implementation of a json custom entry in application logs, describing the time it took and the entities Stored in database, updated or unchaged.

![Capture d’écran du 2022-12-21 14-51-46](https://user-images.githubusercontent.com/118289250/208922462-ab4b7a7e-9bf5-4695-8126-97903b80d534.png)

2022-12-21 15:50 UTC, gdurand-cs requested changes

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/association/DefaultAssociation.java
> -            final var containerRef = EntityProcessing.fromEntity(entityCopy, EntityState.UNCHANGED);
EntityState doit être uniquement sur NEW pour les copies et non sur l'original qui elle est UNCHANGED.
Revoir également le cas à ne pas créer un nouveau EntityProcessing lorsqu'on se sert de l'original.

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/entity/EntityStatistics.java
> +    }
Remarque: Redondant tu as la possibilité de faire l'appel d'une fonction vers l'autre

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/entity/EntityStatistics.java
> +    public void retrieveProcessingTime(long milliSeconds, Class<? extends DefaultEntity> entityClass) {
Remarque: Attention au nom de classe ou de fonction que tu utilise; Ici à en lire le nom de la fonction on s'attend à récupérer quelque chose mais on a un void. Utiliser set plutôt que retrieve serait plus judicieux

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/entity/EntityStatistics.java
> +    public String printEntitiesCreated() {
Tu l'utilise toujours ? N'est-elle pas remplacé par le Jackson databind ?

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/mapper/EntityCache.java
> +
Oublie ???

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/processor/ProcessorOrchestrator.java
> +import eu.csgroup.coprs.monitoring.common.datamodel.entities.MissingProducts;
Pas certains que cet import soit utile

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/common/src/main/java/eu/csgroup/coprs/monitoring/common/ingestor/EntityIngestor.java
> -     */
Ce n'est pas intéressant comme commentaire ?

2022-12-21 15:50 UTC, gdurand-cs commented on trace-processor/applications/processor/trace-filter/src/test/resources/trace-filtered.json
> +{
Tu as changé quelque chose en particulier sur le fichier de test ?

2022-12-21 16:06 UTC, RomainDUCLERCQ commented on trace-processor/applications/processor/trace-filter/src/test/resources/trace-filtered.json
> +{
Non, rien de particulier, j'ai formaté le fichier, ca a fait des retours à la ligne pour un peu plus de visibilité

2022-12-22 08:40 UTC, RomainDUCLERCQ commented on trace-processor/applications/sink/trace-ingestor/src/main/java/eu/csgroup/coprs/monitoring/traceingestor/processor/ProcessorOrchestrator.java
> +import eu.csgroup.coprs.monitoring.common.datamodel.entities.MissingProducts;
ah c'est un reformatage qui a enlevé l'espace au début de la ligne, voilà tout

2022-12-22 10:46 UTC, gdurand-cs approved these changes

2022-12-22 11:15 UTC, merged